#include "pgmspace.h"

// memcpy_P(buf, LIMITWINDOW_IMAGE, 20480);

#define LIMITWINDOW_IMAGE_LEN 20480
#define LIMITWINDOW_IMAGE_W 160
#define LIMITWINDOW_IMAGE_H 128

extern const uint16_t LIMITWINDOW_IMAGE[20480] PROGMEM;

#define LIMITWINDOW_draw(x,y) TFT_drawPixmap(x, y, LIMITWINDOW_IMAGE_W, LIMITWINDOW_IMAGE_H,LIMITWINDOW_IMAGE)



