#include "pgmspace.h"

// memcpy_P(buf, TESTLICZNIK_IMAGE, 20480);

#define TESTLICZNIK_IMAGE_LEN 20480
#define TESTLICZNIK_IMAGE_W 160
#define TESTLICZNIK_IMAGE_H 128

extern const uint16_t TESTLICZNIK_IMAGE[20480] PROGMEM;

#define TESTLICZNIK_draw(x,y) TFT_drawPixmap(x, y, TESTLICZNIK_IMAGE_W, TESTLICZNIK_IMAGE_H,TESTLICZNIK_IMAGE)



